eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka/
server:
  port: 8888
spring:
  application:
    name: gateway-service-zuul
zuul:
  routes:
    user:
      path: /user/api/**
      serviceId: my-lawyer-user-web
    index:
      path: /index/api/**
      serviceId: my-lawyer-index-web

